spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format-sql: true
        auto_quote_keyword: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carpartspicker?serverTimezone=UTC

    #Local use :
    username: louis
    password: zapo

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  servlet:
    context-path: /SpringRestHibernate

management:
  endpoint:
    logfile:
      enabled: true
      external-file: /var/log/tomcat9/CIADSpringRestHibernate.log
  endpoints:
    enabled-by-default: true
    web:
      base-path: /management
      exposure:
        include: "*"
  security:
    enabled: false
    roles: ROLE_ADMIN
